<?php

namespace Tensor\Tests;

use RuntimeException;
use PHPUnit\Framework\TestCase;

/**
 * Pins the compiler this extension is generated by, and the state of the Buffer
 * opt-in.
 *
 * The Tensor\Buffer kernel class landed three commits after Zephir 1.5.0 and is
 * in no tagged release, so `phalcon/zephir: ^1.0` cannot build the buffer-backed
 * migration at all.
 *
 * Switching compilers regenerates all 113 files under ext/ — the dev-development
 * config.m4 template lists kernel/buffer.c unconditionally, for one thing — so
 * the switch is made on its own, with the Buffer still switched off. That way
 * SnapshotTest going red afterwards means the compiler changed behaviour, and
 * not the feature. Enabling the Buffer is the next step, and is separately
 * reviewable.
 *
 * @coversNothing
 */
class ToolchainTest extends TestCase
{
    /**
     * @test
     */
    public function zephirIsPinnedToDevDevelopment() : void
    {
        /** @var array{require-dev?: array<string, string>} $composer */
        $composer = json_decode($this->read('composer.json'), true);

        $this->assertSame('dev-development', $composer['require-dev']['phalcon/zephir'] ?? null);
    }

    /**
     * Proof that ext/ was actually regenerated under the new compiler rather
     * than left as whatever 1.5.0 emitted: kernel/buffer.c only appears in the
     * dev-development config.m4 template.
     *
     * @test
     */
    public function generatedConfigComesFromTheNewCompiler() : void
    {
        $this->assertStringContainsString('kernel/buffer.c', $this->read('ext/config.m4'));
    }

    /**
     * The compiler emits these into ext/php_<extension-name>.h — which is
     * php_tensor_ext.h here, not php_tensor.h. Grepping the wrong one passes
     * whatever the truth is, which is how a Stage 2 check could look green
     * while the Buffer was never switched on.
     *
     * @test
     */
    public function bufferIsEnabled() : void
    {
        $header = $this->read('ext/php_tensor_ext.h');

        $this->assertStringContainsString('#define ZEPHIR_BUFFER_ENABLED 1', $header);
        $this->assertStringContainsString('#define ZEPHIR_BUFFER_NAMESPACE "Tensor"', $header);
    }

    /**
     * The opt-in is a strict identity check against JSON true, so `1` or
     * `"true"` would silently do nothing at all.
     *
     * @test
     */
    public function theBufferOptInIsTheBooleanTrue() : void
    {
        /** @var array{kernel-classes?: array<string, mixed>} $config */
        $config = json_decode($this->read('config.json'), true);

        $this->assertTrue($config['kernel-classes']['buffer'] ?? null);
    }

    /**
     * @test
     */
    public function handWrittenCSurvivedRegeneration() : void
    {
        foreach (['arithmetic', 'comparison', 'linear_algebra', 'signal_processing', 'settings'] as $unit) {
            $this->assertFileExists(dirname(__DIR__) . "/ext/include/{$unit}.c");
            $this->assertFileExists(dirname(__DIR__) . "/ext/include/{$unit}.h");
        }
    }

    /**
     * The pseudoinverse fix lives in hand-written C, which `zephir fullclean`
     * has no business touching. If this fails, the regeneration ate it.
     *
     * @test
     */
    public function thePseudoinverseFixSurvivedRegeneration() : void
    {
        $this->assertStringContainsString(
            'CblasTrans, CblasTrans, n, m, k, 1.0, vvt',
            $this->read('ext/include/linear_algebra.c')
        );
    }

    private function read(string $file) : string
    {
        $contents = file_get_contents(dirname(__DIR__) . '/' . $file);

        if ($contents === false) {
            throw new RuntimeException("Cannot read {$file}.");
        }

        return $contents;
    }
}
